added inventory_adjustment entity and remove method added
herobullion/qbo pull request #2
Opened 2024-09-20 15:15 UTC by farjad6

2024-09-20 15:29 UTC, shaunek-hero commented
The title of your PR needs to be more descriptive. Remember that the PR title ends up being the comment on a commit.

2024-09-20 15:32 UTC, shaunek-hero commented
Probably should update the bottom of the README file

2024-09-20 15:40 UTC, farjad6 commented
> The title of your PR needs to be more descriptive. Remember that the PR title ends up being the comment on a commit.

noted sir,

2024-09-20 15:41 UTC, farjad6 commented
> Probably should update the bottom of the README file

updated

2024-09-20 16:40 UTC, shaunek-hero requested changes

2024-09-20 16:40 UTC, shaunek-hero commented on src/entity/inventory-adjustment.ts
> +  "PrivateNote"?: string,
Why do some of these keys like `PrivateNote` and `AdjustAccountRef`, etc have double quotes around them? Can't we exclude the double quotes since these keys don't have odd characters like a hyphen?

2024-09-20 16:40 UTC, shaunek-hero commented on src/lib/utils.ts
> +    minorversion: 70
Nice catch!

2024-09-20 16:40 UTC, shaunek-hero commented on src/remove.ts
> +export type RemoveResponse<T extends QBOQueryableEntityType> = {
Are you sure this is the right structure for a response? I looked at the delete operation in several objects in QBO's documentation and it seems like it takes a different shape than this.

2024-09-20 16:40 UTC, shaunek-hero commented on src/remove.ts
> +export const remove = ({
I'm slightly partial to calling all this functionality "delete" instead of "remove." Would you consider renaming all these types and this function name and this file, etc to be "delete" instead?

2024-09-23 16:08 UTC, shaunek-hero approved these changes

2024-09-23 16:08 UTC, merged